-- MySQL Script generated by MySQL Workbench
-- 02/12/16 17:03:31
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mimic
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mimic
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mimic` DEFAULT CHARACTER SET utf8 ;
USE `mimic` ;

-- -----------------------------------------------------
-- Table `mimic`.`strips`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mimic`.`strips` (
  `idstrips` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(255) NOT NULL,
  `image1` VARCHAR(255) NULL,
  `image2` VARCHAR(255) NULL,
  `image3` VARCHAR(255) NULL,
  `texte1` VARCHAR(255) NULL,
  `texte2` VARCHAR(255) NULL,
  `texte3` VARCHAR(255) NULL,
  `date_creation` VARCHAR(45) NULL,
  `nbre_like` INT NULL,
  PRIMARY KEY (`idstrips`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mimic`.`etiquettes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mimic`.`etiquettes` (
  `idetiquettes` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(90) NULL,
  PRIMARY KEY (`idetiquettes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mimic`.`etiquettes_has_strips`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mimic`.`etiquettes_has_strips` (
  `etiquettes_idetiquettes` INT NOT NULL,
  `strips_idstrips` INT NOT NULL,
  PRIMARY KEY (`etiquettes_idetiquettes`, `strips_idstrips`),
  INDEX `fk_etiquettes_has_strips_strips1_idx` (`strips_idstrips` ASC),
  INDEX `fk_etiquettes_has_strips_etiquettes_idx` (`etiquettes_idetiquettes` ASC),
  CONSTRAINT `fk_etiquettes_has_strips_etiquettes`
    FOREIGN KEY (`etiquettes_idetiquettes`)
    REFERENCES `mimic`.`etiquettes` (`idetiquettes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_etiquettes_has_strips_strips1`
    FOREIGN KEY (`strips_idstrips`)
    REFERENCES `mimic`.`strips` (`idstrips`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
